CREATE TABLE Fakt (
   BRFAK CHAR(6), 
   BARCODE CHAR(13), 
   NAZART CHAR(40), 
   JMERE CHAR(3), 
   KOLICINA DECIMAL(12,3), 
   PRODCEN DECIMAL(12,3), 
   RABAT DECIMAL(15,9), 
   TARGR CHAR(3), 
   PSPOR DECIMAL(6,3), 
   OPISART BLOB);


COMMIT;

