CREATE TABLE FIRME (
   SIFRA CHAR(3), 
   NAZIV CHAR(30), 
   VLASNIK CHAR(30), 
   MESTO CHAR(30), 
   MESTOIZD CHAR(30), 
   ULICA CHAR(50), 
   RACUN CHAR(20), 
   PIB CHAR(13), 
   PEPDV CHAR(13), 
   OBVZNKPDV INTEGER, 
   KONTAKT CHAR(50), 
   RACUN1 CHAR(20), 
   RACUN2 CHAR(20), 
   RACUN3 CHAR(20), 
   RACUN4 CHAR(20), 
   RACUN5 CHAR(20));

INSERT INTO FIRME
  (SIFRA, NAZIV, VLASNIK, MESTO, MESTOIZD, ULICA, RACUN, PIB, PEPDV, OBVZNKPDV, KONTAKT, RACUN1, RACUN2, RACUN3, RACUN4, RACUN5)
VALUES
  ("000", "MT Codes", "Milkan T.", "Banja Luka", "", "Karadjordjeva 52", "[tekuci racun]", "111111111111", "111111111111", 0, "Milkan T.", "", "", "", "", "");

COMMIT;

