CREATE TABLE MdArt (
   SIFRA CHAR(6), 
   BARCODE CHAR(13), 
   NAZIV CHAR(40), 
   JMERE CHAR(3), 
   TARGR CHAR(3), 
   NABCEN DECIMAL(12,3), 
   PRODCEN DECIMAL(12,3), 
   POPKOL DECIMAL(12,3), 
   ULAZ DECIMAL(12,3), 
   IZLAZ DECIMAL(12,3), 
   ZALIHA DECIMAL(12,3), 
   USLUGA INTEGER, 
   OPIS BLOB);

INSERT INTO MdArt
  (SIFRA, BARCODE, NAZIV, JMERE, TARGR, NABCEN, PRODCEN, POPKOL, ULAZ, IZLAZ, ZALIHA, USLUGA, OPIS)
VALUES
  ("", "", "", "", "", 0, 0, 0, 0, 0, 0, 0, "");
INSERT INTO MdArt
  (SIFRA, BARCODE, NAZIV, JMERE, TARGR, NABCEN, PRODCEN, POPKOL, ULAZ, IZLAZ, ZALIHA, USLUGA, OPIS)
VALUES
  ("000002", "0000000000001", "Bootstrap thema", "KOM", "017", 0, 50, 0, 0, 0, 0, 0, "");
INSERT INTO MdArt
  (SIFRA, BARCODE, NAZIV, JMERE, TARGR, NABCEN, PRODCEN, POPKOL, ULAZ, IZLAZ, ZALIHA, USLUGA, OPIS)
VALUES
  ("000003", "2", "Dizajn majice", "KOM", "017", 0, 100, 0, 0, 0, 0, 1, "");
INSERT INTO MdArt
  (SIFRA, BARCODE, NAZIV, JMERE, TARGR, NABCEN, PRODCEN, POPKOL, ULAZ, IZLAZ, ZALIHA, USLUGA, OPIS)
VALUES
  ("000004", "3", "DDR 1 Ram memorija", "KOM", "017", 0, 15, 0, 0, 0, 0, 0, "DDR 1 400Mhz
");
INSERT INTO MdArt
  (SIFRA, BARCODE, NAZIV, JMERE, TARGR, NABCEN, PRODCEN, POPKOL, ULAZ, IZLAZ, ZALIHA, USLUGA, OPIS)
VALUES
  ("000006", "5", "Cerupanje koka", "KOM", "017", 0, 1, 0, 0, 0, 0, 1, "Cerupanje koka bez klanja
");
INSERT INTO MdArt
  (SIFRA, BARCODE, NAZIV, JMERE, TARGR, NABCEN, PRODCEN, POPKOL, ULAZ, IZLAZ, ZALIHA, USLUGA, OPIS)
VALUES
  ("000005", "4", "DDR2 ram memorija", "KOM", "020", 0, 0, 0, 0, 0, 0, 0, "DDR 2 800Mhz
");

COMMIT;

